#!/usr/bin/env python3
"""
train.py — ArtBridge complete training + TFLite export pipeline.

QUICK START:
    1. Run setup first (creates dataset/ folders + synthetic unknowns):
           python3 setup_dataset.py

    2. Add your product images:
           dataset/bamboo_basket/    ← add 100-300 photos here
           dataset/ceramic_plate/    ← add 100-300 photos here
           dataset/clay_pot/         ← add 100-300 photos here
           ... (same for all 10 product classes)
           dataset/unknown/          ← auto-filled by setup_dataset.py

    3. Train:
           python3 train.py

    4. Copy to Pi:
           scp model.tflite pi@raspberrypi:~/Desktop/artbridge_kiosk/

DATASET STRUCTURE REQUIRED:
    dataset/
        bamboo_basket/        100-300 images
        ceramic_plate/        100-300 images
        clay_pot/             100-300 images
        handwoven_mat/        100-300 images
        jute_bag/             100-300 images
        palm_leaf_items/      100-300 images
        pottery_vase/         100-300 images
        terracotta_statue/    100-300 images
        traditional_painting/ 100-300 images
        wooden_carving/       100-300 images
        unknown/              200-400 images (auto-generated by setup_dataset.py)
"""

import os
import sys
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras import layers, models, callbacks
import cv2

# ─────────────────────────────────────────────────────────────────────────────
#  CONFIG  — edit these if needed
# ─────────────────────────────────────────────────────────────────────────────
IMG_SIZE        = 224
BATCH_SIZE      = 16
EPOCHS_FROZEN   = 10
EPOCHS_FINETUNE = 15
DATASET_DIR     = "dataset"
MODEL_H5        = "model.h5"
MODEL_TFLITE    = "model.tflite"
MODEL_TFLITE_Q  = "model_quantised.tflite"

EXPECTED_CLASSES = [
    "bamboo_basket", "ceramic_plate", "clay_pot", "handwoven_mat",
    "jute_bag", "palm_leaf_items", "pottery_vase", "terracotta_statue",
    "traditional_painting", "wooden_carving", "unknown",
]

# ─────────────────────────────────────────────────────────────────────────────
#  PRE-FLIGHT CHECKS  — clear errors before training starts
# ─────────────────────────────────────────────────────────────────────────────
print("\n" + "=" * 60)
print("  ArtBridge Training Pipeline")
print("=" * 60)

# Check dataset folder exists
if not os.path.isdir(DATASET_DIR):
    print(f"\n❌  ERROR: '{DATASET_DIR}/' folder not found.")
    print("   You need to create it and add images first.")
    print()
    print("   STEP 1 — Create folder structure:")
    print("       python3 setup_dataset.py")
    print()
    print("   STEP 2 — Add product images to each folder:")
    for cls in EXPECTED_CLASSES:
        print(f"       dataset/{cls}/   ← add photos here")
    print()
    print("   STEP 3 — Re-run training:")
    print("       python3 train.py")
    sys.exit(1)

# Check which class folders exist and have images
print(f"\n📂  Checking dataset/ ...")
missing_folders  = []
empty_folders    = []
folder_counts    = {}

for cls in EXPECTED_CLASSES:
    folder = os.path.join(DATASET_DIR, cls)
    if not os.path.isdir(folder):
        missing_folders.append(cls)
        continue
    images = [
        f for f in os.listdir(folder)
        if f.lower().endswith((".jpg", ".jpeg", ".png", ".bmp", ".webp"))
    ]
    folder_counts[cls] = len(images)
    if len(images) == 0:
        empty_folders.append(cls)

# Report folder status
for cls in EXPECTED_CLASSES:
    if cls in missing_folders:
        status = "❌  MISSING"
        count  = 0
    elif cls in empty_folders:
        status = "⚠️   EMPTY"
        count  = 0
    else:
        count  = folder_counts.get(cls, 0)
        status = f"✅  {count} images"
    print(f"   dataset/{cls:25s}  {status}")

# Hard stop if no folders exist at all
if len(missing_folders) == len(EXPECTED_CLASSES):
    print("\n❌  No class folders found inside dataset/.")
    print("   Run:  python3 setup_dataset.py")
    sys.exit(1)

# Warn about missing/empty folders but allow training to continue
# if at least 2 classes have images (TF needs ≥2 classes)
usable = [c for c in EXPECTED_CLASSES
          if c not in missing_folders and c not in empty_folders]

if len(usable) < 2:
    print(f"\n❌  Only {len(usable)} class folder(s) have images.")
    print("   Need at least 2 classes with images to train.")
    print("   Add images to the empty folders and try again.")
    sys.exit(1)

if missing_folders or empty_folders:
    problem = missing_folders + empty_folders
    print(f"\n⚠️   {len(problem)} folder(s) are missing/empty — they will be skipped.")
    print("   Training with the remaining classes is fine, but accuracy")
    print("   on skipped classes will be zero. Add images and retrain later.")

total_images = sum(folder_counts.values())
print(f"\n✅  Ready to train with {len(usable)} classes, {total_images} total images.")

# ─────────────────────────────────────────────────────────────────────────────
#  DATA GENERATORS
# ─────────────────────────────────────────────────────────────────────────────
print("\n" + "=" * 60)
print("  Setting up data generators ...")
print("=" * 60)

train_datagen = ImageDataGenerator(
    rescale=1.0 / 255,
    validation_split=0.2,
    rotation_range=25,
    width_shift_range=0.12,
    height_shift_range=0.12,
    shear_range=0.10,
    zoom_range=0.20,
    horizontal_flip=True,
    fill_mode="nearest",
    brightness_range=[0.65, 1.35],
    channel_shift_range=20.0,
)

val_datagen = ImageDataGenerator(
    rescale=1.0 / 255,
    validation_split=0.2,
)

train_data = train_datagen.flow_from_directory(
    DATASET_DIR,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode="categorical",
    subset="training",
    shuffle=True,
    seed=42,
)

val_data = val_datagen.flow_from_directory(
    DATASET_DIR,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode="categorical",
    subset="validation",
    shuffle=False,
    seed=42,
)

NUM_CLASSES = train_data.num_classes
print(f"\n   Classes found  : {NUM_CLASSES}")
print(f"   Training images: {train_data.samples}")
print(f"   Validation img : {val_data.samples}")
print(f"\n   Class → index mapping:")
for cls, idx in sorted(train_data.class_indices.items(), key=lambda x: x[1]):
    print(f"     [{idx}] {cls}")

# ─────────────────────────────────────────────────────────────────────────────
#  CLASS WEIGHTS
# ─────────────────────────────────────────────────────────────────────────────
try:
    from sklearn.utils.class_weight import compute_class_weight
    cw = compute_class_weight(
        class_weight="balanced",
        classes=np.arange(NUM_CLASSES),
        y=train_data.classes,
    )
    class_weights = {i: float(w) for i, w in enumerate(cw)}
    print("\n⚖️   Class weights (balanced):")
    for cls, idx in sorted(train_data.class_indices.items(), key=lambda x: x[1]):
        print(f"     [{idx}] {cls:25s} weight={class_weights[idx]:.3f}")
except ImportError:
    print("\n⚠️   sklearn not installed — training without class weights.")
    print("   Install with:  pip install scikit-learn")
    class_weights = None

# ─────────────────────────────────────────────────────────────────────────────
#  MODEL
# ─────────────────────────────────────────────────────────────────────────────
print("\n" + "=" * 60)
print("  Building model ...")
print("=" * 60)

base = MobileNetV2(
    weights="imagenet",
    include_top=False,
    input_shape=(IMG_SIZE, IMG_SIZE, 3),
)
base.trainable = False

model = models.Sequential([
    base,
    layers.GlobalAveragePooling2D(),
    layers.BatchNormalization(),
    layers.Dense(256, activation="relu"),
    layers.Dropout(0.50),
    layers.Dense(128, activation="relu"),
    layers.Dropout(0.30),
    layers.Dense(NUM_CLASSES, activation="softmax"),
], name="artisan_classifier")

model.summary()

# ─────────────────────────────────────────────────────────────────────────────
#  CALLBACKS
# ─────────────────────────────────────────────────────────────────────────────
checkpoint = callbacks.ModelCheckpoint(
    MODEL_H5,
    monitor="val_accuracy",
    save_best_only=True,
    verbose=1,
)
reduce_lr = callbacks.ReduceLROnPlateau(
    monitor="val_loss",
    factor=0.4,
    patience=3,
    min_lr=1e-7,
    verbose=1,
)

# ─────────────────────────────────────────────────────────────────────────────
#  PHASE 1 — Head only, base frozen
# ─────────────────────────────────────────────────────────────────────────────
print("\n" + "=" * 60)
print("  PHASE 1 — Training head only (base frozen)")
print(f"  Up to {EPOCHS_FROZEN} epochs, LR=0.001")
print("=" * 60)

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss="categorical_crossentropy",
    metrics=["accuracy"],
)

model.fit(
    train_data,
    validation_data=val_data,
    epochs=EPOCHS_FROZEN,
    class_weight=class_weights,
    callbacks=[
        callbacks.EarlyStopping(
            monitor="val_accuracy", patience=5,
            restore_best_weights=True, verbose=1,
        ),
        reduce_lr,
        checkpoint,
    ],
    verbose=1,
)

# ─────────────────────────────────────────────────────────────────────────────
#  PHASE 2 — Fine-tune top 30 MobileNetV2 layers
# ─────────────────────────────────────────────────────────────────────────────
print("\n" + "=" * 60)
print("  PHASE 2 — Fine-tuning top 30 MobileNetV2 layers")
print(f"  Up to {EPOCHS_FINETUNE} epochs, LR=0.00001")
print("=" * 60)

base.trainable = True
freeze_until = len(base.layers) - 30
for layer in base.layers[:freeze_until]:
    layer.trainable = False

print(f"  Trainable layers: {sum(1 for l in model.layers if l.trainable)}")

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),
    loss="categorical_crossentropy",
    metrics=["accuracy"],
)

model.fit(
    train_data,
    validation_data=val_data,
    epochs=EPOCHS_FINETUNE,
    class_weight=class_weights,
    callbacks=[
        callbacks.EarlyStopping(
            monitor="val_accuracy", patience=6,
            restore_best_weights=True, verbose=1,
        ),
        reduce_lr,
        checkpoint,
    ],
    verbose=1,
)

# Final save
model.save(MODEL_H5)
print(f"\n✅  model.h5 saved → {os.path.abspath(MODEL_H5)}")

# ─────────────────────────────────────────────────────────────────────────────
#  TFLITE CONVERSION — float32
# ─────────────────────────────────────────────────────────────────────────────
print("\n" + "=" * 60)
print("  CONVERTING → model.tflite (float32)")
print("=" * 60)

converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_bytes = converter.convert()
with open(MODEL_TFLITE, "wb") as f:
    f.write(tflite_bytes)
size_mb = os.path.getsize(MODEL_TFLITE) / 1024 / 1024
print(f"✅  model.tflite saved  ({size_mb:.1f} MB)")

# Verify
interp = tf.lite.Interpreter(model_path=MODEL_TFLITE)
interp.allocate_tensors()
inp_d = interp.get_input_details()[0]
out_d = interp.get_output_details()[0]
dummy = np.random.rand(1, IMG_SIZE, IMG_SIZE, 3).astype(np.float32)
interp.set_tensor(inp_d["index"], dummy)
interp.invoke()
test_out = interp.get_tensor(out_d["index"])[0]
print(f"   Verification: output sum={test_out.sum():.4f} (≈1.0 ✅)")

# ─────────────────────────────────────────────────────────────────────────────
#  TFLITE CONVERSION — int8 quantised (recommended for Pi)
# ─────────────────────────────────────────────────────────────────────────────
print("\n" + "=" * 60)
print("  CONVERTING → model_quantised.tflite (int8)")
print("  (smaller + faster on Raspberry Pi)")
print("=" * 60)

# Collect calibration images from dataset
cal_images = []
for root, _, files in os.walk(DATASET_DIR):
    for fname in files:
        if fname.lower().endswith((".jpg", ".jpeg", ".png")):
            img = cv2.imread(os.path.join(root, fname))
            if img is None:
                continue
            img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
            cal_images.append(img.astype(np.float32) / 255.0)
            if len(cal_images) >= 100:
                break
    if len(cal_images) >= 100:
        break

if not cal_images:
    print("   ⚠️   No calibration images — using random data.")
    cal_images = [np.random.rand(IMG_SIZE, IMG_SIZE, 3).astype(np.float32)
                  for _ in range(50)]

print(f"   Calibrating with {len(cal_images)} images ...")

def _rep_dataset():
    for img in cal_images:
        yield [np.expand_dims(img, 0)]

conv_q = tf.lite.TFLiteConverter.from_keras_model(model)
conv_q.optimizations = [tf.lite.Optimize.DEFAULT]
conv_q.representative_dataset = _rep_dataset
conv_q.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
conv_q.inference_input_type  = tf.uint8
conv_q.inference_output_type = tf.uint8

try:
    tflite_q = conv_q.convert()
    with open(MODEL_TFLITE_Q, "wb") as f:
        f.write(tflite_q)
    size_q = os.path.getsize(MODEL_TFLITE_Q) / 1024 / 1024
    reduction = (1 - size_q / size_mb) * 100
    print(f"✅  model_quantised.tflite saved  ({size_q:.1f} MB, {reduction:.0f}% smaller)")
except Exception as exc:
    print(f"⚠️   Quantised conversion failed: {exc}")
    print("   Use model.tflite (float32) instead — it works fine on Pi.")

# ─────────────────────────────────────────────────────────────────────────────
#  FINAL SUMMARY
# ─────────────────────────────────────────────────────────────────────────────
print("\n" + "=" * 60)
print("  TRAINING COMPLETE ✅")
print("=" * 60)
print()
print(f"  Files produced:")
print(f"    model.h5                 → {os.path.abspath(MODEL_H5)}")
print(f"    model.tflite             → {os.path.abspath(MODEL_TFLITE)}")
if os.path.exists(MODEL_TFLITE_Q):
    print(f"    model_quantised.tflite   → {os.path.abspath(MODEL_TFLITE_Q)}")
print()
print("  To deploy on Raspberry Pi:")
print("    1. Install runtime (once):")
print("         pip install tflite-runtime --break-system-packages")
print("    2. Copy model.tflite to the Pi:")
print(f"         scp model.tflite pi@<IP>:~/Desktop/artbridge_kiosk/")
print("       Or for best Pi performance use model_quantised.tflite")
print("       (rename it to model.tflite before copying)")
print("    3. Run the app:")
print("         python3 main.py --mock")
print()
print("  Class → index mapping (verify against CLASSES in ml_service.py):")
for cls, idx in sorted(train_data.class_indices.items(), key=lambda x: x[1]):
    print(f"    [{idx}] '{cls}'")
